/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.UserAccount.UserAccount;
import model.WorkQueue.BookAppointment;
import model.WorkQueue.WorkRequest;

/**
 *
 * @author Akshatha
 */
public class DoctorAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorAdminJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount user;
    String hospname;
    
    public DoctorAdminJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        viewTable();
        jPanel1.setVisible(false);
    }
    
    public void viewTable(){

        DefaultTableModel dtm = (DefaultTableModel) docDetails.getModel();
        dtm.setRowCount(0);
        
       if( system.getWorkQueue()!=null){
        for(WorkRequest wq :system.getWorkQueue().getWorkReqList()) {
            if(wq instanceof BookAppointment){
            Object row[] = new Object[4];
            row[0] = wq;
            row[1] = wq.getMsg();
            row[2] = wq.getStat();
            row[3] = wq.getReqDate();
            dtm.addRow(row);
        }}}
    }
    
    public void viewTable1(String name){
        
        DefaultTableModel dtm = (DefaultTableModel) docDetails1.getModel();
        dtm.setRowCount(0);
        
        int row1 = docDetails.getSelectedRow();
        int column = 0;
        String value = docDetails.getModel().getValueAt(row1, column).toString();
        for(WorkRequest wq : system.getWorkQueue().getWorkReqList()) {
            if(wq instanceof BookAppointment){
                System.out.println("reciever "+value);
                if(wq.getSender().getEmployee().getName().equals(value)){
//                System.out.println("comm" + ((BookAppointment) wq).getComments());
           Object row[] = new Object[5];
            row[0] = wq.getSender().getEmployee().getName();
            System.out.println("meds are" +((BookAppointment) wq).getMed().getMedicine());
            
                for(int i=1;i<=(((BookAppointment) wq).getMed().getMedicine()).size();i++){
                    for(String m:((BookAppointment) wq).getMed().getMedicine()){
                    System.out.println(((BookAppointment) wq).getMed().getMedicine().size());
                    row[i] = m;
                    i++;
            }
            }
            row[4]=((BookAppointment) wq).getComment();
            dtm.addRow(row);
            }}}
           
        
         jPanel1.setVisible(true);
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        docDetails = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        docDetails1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient name", "Patient symtoms", "Patient Booking Status", "Booked Time"
            }
        ));
        jScrollPane1.setViewportView(docDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 700, 90));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check prescription");
        jButton1.setPreferredSize(new java.awt.Dimension(156, 43));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 210, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        docDetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "medicine 1", "medicine 2", "medicine 3", "comments"
            }
        ));
        jScrollPane2.setViewportView(docDetails1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 720, 140));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Create a prescription");
        jButton2.setPreferredSize(new java.awt.Dimension(156, 43));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 210, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("DOCTOR DASHBOARD");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 230, 30));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, -30, 330, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = docDetails.getSelectedRow();
        int column = 0;
        String value = docDetails.getModel().getValueAt(row, column).toString();
        if(row < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        viewTable1(value);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = docDetails.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookAppointment pa = (BookAppointment)docDetails.getValueAt(selectedRow,0);
        PrescriptionJPanel prescriptionJPanel = new PrescriptionJPanel(userProcessContainer, system,pa);
        userProcessContainer.add("add Prescription", prescriptionJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable docDetails;
    private javax.swing.JTable docDetails1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
