/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DeliveryMan;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.DB4OUtil.DB4OUtil;
import model.DeliveryMan.DeliveryManDirectory;
import model.EcoSystem;
import model.Patient.Patient;
import model.Pharmacist.PharamacyAdmin;
import model.UserAccount.UserAccount;
import model.WorkQueue.OrderInventoryWorkRequest;
import model.WorkQueue.PharmacyOrder;
import model.WorkQueue.PlaceNewOrderWorkRequest;
import model.WorkQueue.WorkRequest;

/**
 *
 * @author Akshatha
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {
    
      private JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem system;
    Patient pat;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    DefaultTableModel dtm;
    ArrayList<Patient> array1;
    List<PharmacyOrder> orderItemList = new ArrayList<PharmacyOrder>();
    WorkRequest workrequest;
    private PharamacyAdmin pharObj;
    PlaceNewOrderWorkRequest placeWorkRequest;
    String patname;
    String pharName;
    DeliveryManDirectory delDir;


    /**
     * Creates new form DeliveryManWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.system = business;
      
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        delManTbl = new javax.swing.JTable();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignJButton.setBackground(new java.awt.Color(51, 51, 255));
        assignJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.setPreferredSize(new java.awt.Dimension(156, 43));
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        processJButton.setBackground(new java.awt.Color(51, 51, 255));
        processJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        processJButton.setText("Delivered");
        processJButton.setPreferredSize(new java.awt.Dimension(156, 43));
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });
        add(processJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        refreshJButton.setBackground(new java.awt.Color(51, 51, 255));
        refreshJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refreshJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshJButton.setText("Refresh");
        refreshJButton.setPreferredSize(new java.awt.Dimension(156, 43));
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        delManTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Name", "Assigned by", "Status", "Date Assigned"
            }
        ));
        jScrollPane1.setViewportView(delManTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 700, 100));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("DELIVERY MAN DASHBOARD");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/delivery.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = delManTbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        } else {
            if (delManTbl.getValueAt(selectedRow, 1).equals("Completed")) {
                JOptionPane.showMessageDialog(null, "Order is already completed!");
            } else {
                WorkRequest request = (WorkRequest) delManTbl.getValueAt(selectedRow, 0);
                request.setStatus("Pending");
                populateTable();
            }

        }
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed

        int selectedRow = delManTbl.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "You must select a row first!");
        }

        WorkRequest request = (WorkRequest) delManTbl.getValueAt(selectedRow, 0);
        if (delManTbl.getValueAt(selectedRow, 1).equals("Completed")) {
            JOptionPane.showMessageDialog(null, "Order is already processed and completed!");
        } else {

            request.setStatus("Delivered");
            populateTable();
        }

        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JTable delManTbl;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables

public void populateTable(){
                DefaultTableModel dtm = (DefaultTableModel) delManTbl.getModel();
        dtm.setRowCount(0);
        System.out.println(system.getWorkQueue().getWorkRequestList());

        for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
            System.out.println(request);
            System.out.println(this.user);
            if(request instanceof PlaceNewOrderWorkRequest|| request instanceof OrderInventoryWorkRequest) {
                if(request.getDeliveryMan()!=null){
            System.out.println(request.getDeliveryMan());
                if (request.getDeliveryMan().equals(this.user)) {
                Object[] row = new Object[4];
                //row[0] = request;
                row[0] = request;
                row[1] = request.getReceiver().getEmployee().getName();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                dtm.addRow(row);
            }
                }
            }
        }
}
}


