/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Enterprise;
import UserCred.userCred;
import UserCred.userCredData;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pratiksannakki
 */
public class SupplyEnt extends javax.swing.JPanel {
javax.swing.JPanel rightPanel;
 userCredData userData;
    /**
     * Creates new form 
     */
    public SupplyEnt(JPanel c) {
        initComponents();
        userData = new userCredData();
        
        
        this.rightPanel=c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selEnt = new javax.swing.JComboBox<>();
        addPwd = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        entUser = new javax.swing.JTable();

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name : ");

        jLabel2.setText("Password :");

        jLabel5.setText("User Type : ");

        selEnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplies", "Hospital", "Lab Admin", "Emergency Contact" }));
        selEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selEntActionPerformed(evt);
            }
        });

        addPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPwdActionPerformed(evt);
            }
        });

        entUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(entUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(addPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(selEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(register)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(back)
                .addGap(186, 186, 186)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(register)
                    .addComponent(jLabel5)
                    .addComponent(selEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         rightPanel.remove(this);
         ((java.awt.CardLayout) rightPanel.getLayout()).next(rightPanel);
    }//GEN-LAST:event_backActionPerformed

    private void selEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selEntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selEntActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        if(!addUser.getText().equals("") && addPwd.getPassword().length!=0)
        {
        
        for(userCred ucd: userData.getUserData())
        {
           if(addUser.getText().toLowerCase().equals(ucd.getUserName().toLowerCase()))
           {
               
               System.out.println(ucd.getUserName().toLowerCase());
               JOptionPane.showMessageDialog(this, "user already exists");
               
              return;
               
           }
        }
           
        userCred uc= userData.addDetails();
        
        uc.setUserName(addUser.getText().toLowerCase());
        uc.setPwd(new String(addPwd.getPassword()));
        
        
        uc.setUserType(selEnt.getSelectedItem().toString());
        //patient pat = patData.addDetails("pratik", UID, 23, "Male",  454545454, "car@gmail.com");
        
        
        populateusercred();
           
        
        }
            
        
        
        else{
            
            JOptionPane.showMessageDialog(this, "Please enter Valid credentials ");
        return;
        }
    }//GEN-LAST:event_registerActionPerformed

    private void addPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField addPwd;
    private javax.swing.JTextField addUser;
    private javax.swing.JButton back;
    private javax.swing.JTable entUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton register;
    private javax.swing.JComboBox<String> selEnt;
    // End of variables declaration//GEN-END:variables

    private void populateusercred() {
        DefaultTableModel model = (DefaultTableModel) entUser.getModel();
        
        model.setRowCount(0);
        for(userCred em : userData.getUserData())
        {
            
            
        Object[] row = new Object[10];
        row[0]=em.getUserName();
        row[1]=em.getUserType();
        
        
        model.addRow(row);
            
        
        }
    }
}
