/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacyAdmin;

import model.EcoSystem;
import model.Employee.Employee;
import model.Pharmacist.PharamacyAdmin;
import model.UserAccount.UserAccount;
import model.WorkQueue.PlaceNewOrderWorkRequest;
import model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aditya Illur
 */
public class PharamacyAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharamacyAdminJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount user;
    private EcoSystem system;
    String pharName;
    String patName;
    PlaceNewOrderWorkRequest newOrder;
    WorkRequest wq;
    Employee emp;
    PharamacyAdmin phar;
    
public PharamacyAdminJPanel(JPanel userProcessContainer, UserAccount ua,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = ua;
        System.out.println("City "+user.getEmployee().getCity());
        System.out.println("User"+user.getEmployee().getName());
        pharName = user.getEmployee().getName();
       
        System.out.println(system.findNetwork(user.getEmployee().getCity()).getEnterpriseDirectory().findEnterprise(user.getEmployee().getName()).getOrganizationDirectory().getPharmacyAdminDirectory());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEmployeeJButton.setBackground(new java.awt.Color(51, 51, 255));
        manageEmployeeJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageEmployeeJButton.setText("Add new medications");
        manageEmployeeJButton.setPreferredSize(new java.awt.Dimension(156, 43));
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, -1));

        manageOrganizationJButton.setBackground(new java.awt.Color(51, 51, 255));
        manageOrganizationJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageOrganizationJButton.setText("Manage Orders");
        manageOrganizationJButton.setPreferredSize(new java.awt.Dimension(156, 43));
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 210, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("PHARMACY ADMIN");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        
        addMedicineJpanel addMed = new addMedicineJpanel(userProcessContainer, system,pharName,user);
        userProcessContainer.add("CreateHospital", addMed);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        
        manageOrderJpanel orderMan = new manageOrderJpanel(userProcessContainer, system, user,pharName, patName);
        userProcessContainer.add("CreateHospital", orderMan);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    // End of variables declaration//GEN-END:variables
}
